#!/bin/bash
# chkconfig: - 85 15
# Short-Description: starts the nginx web server

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="nginx daemon"
NAME=nginx
DAEMON=/opt/nginx-1.10.0/sbin/$NAME
CONFIGFILE=/opt/nginx-1.10.0/conf/$NAME.conf
PIDFILE=/opt/nginx-1.10.0/logs/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME


set -e
[ -x "$DAEMON" ] || exit 0

do_start() {
    $DAEMON -c $CONFIGFILE || echo -n "nginx already running"
}

do_stop() {
    kill -INT `cat $PIDFILE` || echo -n "nginx not running"
}

do_reload() {
    kill -HUP `cat $PIDFILE` || echo -n "nginx can't reload"
}

case "$1" in

    start)
        echo -n "Starting $DESC: $NAME"
        do_start
        echo "."
        ;;

    stop)
        echo -n "Stopping $DESC: $NAME"
        do_stop
        echo "."
        ;;

    reload|graceful)
        echo -n "Reloading $DESC configuration..."
        do_reload
        echo "."
        ;;

    restart)
        echo -n "Restarting $DESC: $NAME"
        do_stop
        do_start
        echo "."
        ;;

    status)
        curl http://127.0.0.1/my_ngx_status
        echo "."
        ;;

    *)
        echo "Usage: $SCRIPTNAME {start|stop|reload|restart}" >&2
        exit 3
        ;;

    esac

exit 0

