#!/bin/bash -e

TRUNK=$PWD
PROJECT_DIR=`dirname $TRUNK`

echo "Enter project path: $PROJECT_DIR"

# activate virtualenv
source $PROJECT_DIR/bin/activate

# clear pyc cache
find $TRUNK -name "*.pyc"|xargs rm -f

# unbuffer console output
python -u app.py ${@:1}
